_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 9
                - 55
                - 77
                - 103
            "2":
                - 1
                - 9
                - 55
                - 77
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.14
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
model_config:
    value:
        alpha_drop: 0.1
        attn_activation: silu
        attn_alpha_channels: 64
        attn_hidden_channels: 64
        attn_value_channels: 16
        distance_function: gaussian
        drop_path_rate: 0.1
        edge_channels: 128
        ffn_activation: silu
        ffn_hidden_channels: 128
        grid_resolution: 18
        lmax_list:
            - 4
        max_neighbors: 20
        max_num_elements: 90
        max_radius: 12
        mmax_list:
            - 2
        norm_type: layer_norm_sh
        num_distance_basis: 512
        num_heads: 4
        num_layers: 4
        num_sphere_samples: 128
        otf_graph: true
        proj_drop: 0
        regress_forces: true
        share_atom_edge_embedding: false
        sphere_channels: 128
        use_atom_edge_embedding: true
        use_attn_renorm: true
        use_gate_act: false
        use_grid_mlp: true
        use_pbc: false
        use_s2_act_attn: false
        use_sep_s2_act: true
        weight_init: uniform
optimizer_config:
    value:
        amsgrad: true
        betas:
            - 0.9
            - 0.999
        lr: 0.0005
        weight_decay: 0
training_config:
    value:
        bz: 8
        clip_grad: true
        datadir: /deepprinciple-proj-dev/datasets/transition-1x/
        ema: false
        gradient_clip_val: 0.1
        lr_schedule_config:
            gamma: 0.85
            step_size: 50
        lr_schedule_type: step
        num_workers: 48
